### ISSUE TITLE
Generating a visualization manually does nothing

### ISSUE THREAD

**Issue by stefanwebo** [softvis-research/Getaviz#98]
Hello,
I tried to generate a visualization. I followed the instructions under:
https://github.com/softvis-research/Getaviz/wiki/Usage   => 
Generating a visualization manually (all platforms)

I attached my settings.properties file:
[settings.zip](https://github.com/softvis-research/Getaviz/files/3531458/settings.zip)
I am using Windows.

When I call http://localhost:8083/ I get the following message:
Visualization has been generated to the output directory.

But the output directory is empty. Just nothing happens.

I need a visualization for the rd metapher in aframe to test my code. There is only an example visualization in x3dom. If this problem is not easy to solve, could you upload the visualization somewhere so I can test on it.

Best regards,
Stefan

**Comment by naraesk** [comment]
Hello Stefan,

thanks for reporting the problem. Most likely this is just another issue with permissions. I'll have to check this later, I guess we have to adopt the docker file.

I attached the RD aframe visualization for the gradle example.
[rd.zip](https://github.com/softvis-research/Getaviz/files/3531912/rd.zip)

Cheers,
David

**Comment by stefanwebo** [comment]
Hello David,
thanks for the fast support. Could you also attach the gradle example for the city metapher, because it has much more classes than the bank example included in the repo.

Best regards,
Stefan

**Comment by naraesk** [comment]
Did you try to generate a visualization using the UI? With version 1.2 this should also work on Windows.

**Comment by stefanwebo** [comment]
I just pulled the latest version now and retried generatrion from UI and manually. In both cases the output / data-gen directory stays empty.

**Comment by naraesk** [comment]
Sure, but what happens when you start the generation from the UI?
The data-gen directory will stay empty anyways, since it is not synchronized with the host.

**Comment by stefanwebo** [comment]
Ah, okay. It takes some minutes and then it opens this url:
http://localhost:8082/ui/index.php?aframe=true&model=city-floor-gradle-aframe&setup=web_a-frame/default&srcDir=data-gen
Then it hangs on the window "Visualization is loading..." forever and nothing happens.

**Comment by naraesk** [comment]
But there is an error message printed to the web console, isn't it?

Most likely the bug is already fixed on development with commit ca713f5a83f1643a778a10281f91995c5f0e7bcb. Could you please test that? So, please checkout development and run `docker-compose down` and `docker-compose up` and try again.

**Comment by stefanwebo** [comment]
Good news! It worked now. I did not test it on the development branch last time.
So I can create a visualisation from the UI now.
How can I save this visualisation now to reuse it?

**Comment by naraesk** [comment]
Glad ot hear that. The visualization will be available under the shown URL even after restarting the container.

**Comment by stefanwebo** [comment]
Ah, okay. Many thanks!

**Comment by mrarnos3108** [comment]
Hi, I am still not able to generate a visualization via UI. I have a quite
simple .jar and I am hosting it on google drive.
Tried it with the newest master and development branch. Same issue as
Stefan. New link is opening, which says "Visualization is loading", but
nothing is happening. Thanks for any help you can provide.

Am Mi., 4. Sept. 2019 um 14:43 Uhr schrieb Stefan <notifications@github.com

**Comment by naraesk** [comment]
Sure. Would you mind open a separate issue for this and provide more information about your setup? If you have updated to a newer version, please notice that you have to rebuild the container and make sure that you are using the new container. This is described [here](https://github.com/softvis-research/Getaviz/wiki/Local%20Development). 

Additionally, please provide the log file of the generator. You can retrive it via `docker cp BACKENDID:/var/lib/jetty/logs/jetty.log jetty.log`. Replace `BACKENDID` with the actual id of the backend container.

**Comment by naraesk** [comment]
Currenlty we are working on migrating the visualizations to a database so we don't operate on file level anymore. This will make the output directory superfluous. Therefore, we will not fix this for the moment, just remove the documenation. If you like to copy the files, you can copy than from the docker container directly.
